% -------------------------------------------------------------------
%  Generated by MATLAB on 11-Oct-2022 08:41:53
%  MATLAB version: 9.9.0.1467703 (R2020b)
% -------------------------------------------------------------------
                                          

bestPath = [25; 32; 50; 29; 47; 34; 42; 28; 46; 48; 33; 38; 45; 27; 39; ...
            44; 40; 37; 49; 30; 36; 8; 16; 21; 7; 19; 20; 11; 3; 6; 15; ...
            12; 2; 14; 22; 17; 24; 23; 4; 10; 9; 13; 1; 5; 18; 26; 31; ...
            43; 35; 41];

cityLocationPlot = LoadCityLocations();
numberOfCitiesPlot = length(cityLocationPlot);
rangePlot = [0 20 0 20];
tspFigurePlot = InitializeTspPlot(cityLocationPlot, rangePlot);
connectionPlot = InitializeConnections(cityLocationPlot);
pathLength = GetPathLength(bestPath, cityLocationPlot);
PlotPath(connectionPlot, cityLocationPlot, bestPath);
xticks(0:2:20)
yticks(0:2:20)
ylabel('y')
xlabel('x')
title(['Best path found (Path length = ', num2str(pathLength), ')'])
axis equal
axis(rangePlot)
disp(['Path length = ', num2str(pathLength)]);